### ISSUE TITLE
Easy motion bug after jumping to mark

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#122]
On bitballoon, when I type ' to jump to a mark, it seems to break easy motion until I refresh the page.  That, is if I:

* Open vimflowy. Enable easymotion, disable other plugins.
* Typing space now causes easymotion to do its thing.
* Press '.
* Press <esc>
* Typing space now causes nothing to happen.

On Chrome, I get the error message:

Caught error: 'Uncaught SyntaxError: Unexpected token u' from  http://vimflowy.bitballoon.com/:1
3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:16059 Error:  SyntaxError: Unexpected token u(…) SyntaxError: Unexpected token u
    at Object.parse (native)
    at http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:21229:44
    at Array.map (native)
    at View.getVisibleRows (http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:21228:19)
    at Object.<anonymous> (http://bitballoon.scdn4.secure.raxcdn.com/bundles/a8b584d59190a2b0828afe6510d8c1d2bfd64157.js:2:15030)
    at KeyHandler.getMotion (http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:16970:31)
    at KeyHandler.getMotion (http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:16670:59)
    at KeyHandler.processMode (http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:16863:23)
    at KeyHandler.processOnce (http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:16826:21)
    at KeyHandler.processKeys (http://bitballoon.scdn4.secure.raxcdn.com/bundles/3e6a08418e2f780bb0fde5e10bb86da3ff751867.js:16819:27)

**Comment by WuTheFWasThat** [comment]
fixed, thanks for the report
