### ISSUE TITLE
TypeError on launch

### ISSUE THREAD

**Issue by alxgnon** [WuTheFWasThat/vimflowy#151]
Here is a dump of the javascript console. Visited locahost:8080 with Chrome after launching the vimflowy server (npm start).

## Error
```
TypeError: Cannot read property 'id' of undefined
    at Data.getLine (http://localhost:8080/js/data.js:124:37)
    at Cursor._getPropertiesFromContext (http://localhost:8080/js/cursor.js:471:24)
    at new Cursor (http://localhost:8080/js/cursor.js:39:12)
    at View.init (http://localhost:8080/js/view.js:254:23)
    at http://localhost:8080/js/index.js:39:12
```

## Full Log
```
Plugin ID Debug Mode status: Registered
Plugin Easy motion status: Registered
Plugin Hello World coffee example status: Registered
Plugin Marks status: Registered
Plugin Time Tracking status: Registered
Plugin Hello World js example status: Registered
getting from local storage save:schemaVersion 1
got nothing, defaulting to 1
getting from local storage save:lastviewroot2 []
got nothing, defaulting to []
getting from local storage save:lastSave 0
got  1458505873377
getting from local storage settings:theme null
got  default-theme
getting from local storage settings:showKeyBindings null
got  true
getting from local storage settings:hotkeys null
got  Object {}
getting from local storage settings:enabledPlugins null
got  Object {Marks: true}
getting from local storage save:macros Object {}
got nothing, defaulting to Object {}
getting from local storage save:lastSave 0
got  1458505873377
setting local storage settings:enabledPlugins Object {Marks: true}
Plugin ID Debug Mode status: Disabled
getting from local storage save:lastSave 0
got  1458505880434
setting local storage settings:enabledPlugins Object {Marks: true}
Plugin Easy motion status: Disabled
getting from local storage save:lastSave 0
got  1458505880446
setting local storage settings:enabledPlugins Object {Marks: true}
Plugin Hello World coffee example status: Disabled
getting from local storage save:lastSave 0
got  1458505880452
setting local storage settings:enabledPlugins Object {Marks: true}
getting from local storage save:plugin:Marks:version null
got  1
Plugin Marks status: Enabling
Plugin Marks status: Enabled
getting from local storage save:lastSave 0
got  1458505880461
setting local storage settings:enabledPlugins Object {Marks: true}
Plugin Time Tracking status: Disabled
getting from local storage save:lastSave 0
got  1458505880859
setting local storage settings:enabledPlugins Object {Marks: true}
Plugin Hello World js example status: Disabled
getting from local storage save:0:children []
got nothing, defaulting to []
Caught error: 'Uncaught TypeError: Cannot read property 'id' of undefined' from  http://localhost:8080/js/data.js:124
Error:  TypeError: Cannot read property 'id' of undefined(…) TypeError: Cannot read property 'id' of undefined
    at Data.getLine (http://localhost:8080/js/data.js:124:37)
    at Cursor._getPropertiesFromContext (http://localhost:8080/js/cursor.js:471:24)
    at new Cursor (http://localhost:8080/js/cursor.js:39:12)
    at View.init (http://localhost:8080/js/view.js:254:23)
    at http://localhost:8080/js/index.js:39:12
Uncaught TypeError: Cannot read property 'id' of undefined
```

**Comment by WuTheFWasThat** [comment]
figured it out.  the state got messed up due to the lodash bug.  (to reproduce, i deleted the lodash file, opened an incognito tab, fixed the lodash file, refreshed).  For now, you can fix it by doing `localStorage.clear()` and refreshing

I'll try to put some guards around this sort of thing happening, though it's not exactly clear how one would want to recover from it in general.  (AFAIK it should only happen if some other error occurs)

**Comment by alxgnon** [comment]
Thanks, `localStorage.clear()` fixes the issue for me.
