### ISSUE TITLE
Importing hotkeys multiple times

### ISSUE THREAD

**Issue by paulfchristiano** [WuTheFWasThat/vimflowy#225]
When I import hotkeys from a file, and then import hotkeys a second time, the second time seems to work poorly:

* Can't load hotkeys the second time.
* If I click "cancel" on the file select dialog, vimflowy crashes with the following error message:

Cannot read property 'name' of undefined

TypeError: Cannot read property 'name' of undefined
    at t.value (http://localhost:3000/build/app.js:53:20294)
    at onChange (http://localhost:3000/build/app.js:53:20813)
    at Object.executeOnChange (http://localhost:3000/build/app.js:36:30520)
    at p.o (http://localhost:3000/build/app.js:102:26448)
    at Object.r (http://localhost:3000/build/app.js:37:2949)
    at a (http://localhost:3000/build/app.js:36:26951)
    at Object.s [as executeDispatchesInOrder] (http://localhost:3000/build/app.js:36:27166)
    at f (http://localhost:3000/build/app.js:33:7216)
    at d (http://localhost:3000/build/app.js:33:7342)
    at Array.forEach (native)

**Comment by WuTheFWasThat** [comment]
ah, fixed the "cancel" case: 
27abbfe539b81c500268578b7e24a526bef6c94a

I couldn't reproduce "Can't load hotkeys the second time".  The UI wasn't updating though, so maybe that was it?  I fixed that as well in the same commit.  

Let me know if you still have an issue
