### ISSUE TITLE
Unable to Export (via keyboard)

### ISSUE THREAD

**Issue by caseros** [WuTheFWasThat/vimflowy#228]
Exporting (via `ctrl+e`[1]) results in:

```
Cannot read property 'exportFile' of undefined

TypeError: Cannot read property 'exportFile' of undefined
    at Function.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5995)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485)
    at Generator.e.(anonymous function) [as next] (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12259)
    at https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5736
    at u (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5514)
    at Function.s.default.registerAction.a.Action.drop (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5842)
    at t.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:18:24)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485)
```

Console:

```app.js:formatted:5918Update took time 0
app.js:formatted:5918forceLoadTree took time 33
app.js:formatted:5918Update took time 6
app.js:formatted:5918 Handling key: ctrl+e
app.js:formatted:5918 Update took time 0
app.js:formatted:5918 Update took time 2
3app.js:formatted:5918 Update took time 0
app.js:formatted:5918 Showing message: No file selected for import!
app.js:formatted:5918 Showing message: Reading in file...
app.js:formatted:5918 Showing message: Loaded new hotkey settings!
app.js:formatted:5918 Update took time 0
app.js:formatted:5918 Handling key: ctrl+e

app.js:formatted:5918 Action: export-file
app.js:formatted:5918 Caught error: 'Uncaught TypeError: Cannot read property 'exportFile' of undefined' from  https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17
app.js:formatted:5918 Error:  Uncaught TypeError: Cannot read property 'exportFile' of undefined TypeError: Cannot read property 'exportFile' of undefined
    at Function.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5995)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485)
    at Generator.e.(anonymous function) [as next] (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12259)
    at https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5736
    at u (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5514)
    at Function.s.default.registerAction.a.Action.drop (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5842)
    at t.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:18:24)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485) TypeError: Cannot read property 'exportFile' of undefined
    at Function.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5995)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485)
    at Generator.e.(anonymous function) [as next] (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12259)
    at https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5736
    at u (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5514)
    at Function.s.default.registerAction.a.Action.drop (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5842)
    at t.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:18:24)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485) {}
app.js:formatted:30706 Uncaught TypeError: Cannot read property 'exportFile' of undefined
    at Function.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5995)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485)
    at Generator.e.(anonymous function) [as next] (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12259)
    at https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5736
    at u (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5514)
    at Function.s.default.registerAction.a.Action.drop (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:17:5842)
    at t.<anonymous> (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:18:24)
    at o (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:12080)
    at Generator._invoke (https://d33wubrfki0l68.cloudfront.net/js/575ac5404703efe1f50a16ad63a92f77ab4179e7/build/app.js:32:13485)
```

[1] Already use `ctrl+s` in chrome; remapped to `ctrl+e`

- Exporting via `Settings` > `Export as JSON/plaintext` works perfectly (As does importing)

- Chrome Version 55.0.2883.95 (64-bit)
- OS X 10.10.3
- Using local storage
- Reproduced in Firefox

Thanks!

**Comment by WuTheFWasThat** [comment]
Whoops!  Fixed in e25e0017b0caabfa837d29ebb893ad4ca161d3b2.  Thanks for reporting.
