### ISSUE TITLE
Unable to compile TypeScript error

### ISSUE THREAD

**Issue by mi-lee** [WuTheFWasThat/vimflowy#258]
I followed the dev setup instructions -- `npm install; npm start;`. It goes awry at `ts-node src/server`. Node version is v6.10.3 and npm is 3.10.10.

```
> ts-node src/server


/vimflowy/node_modules/ts-node/src/index.ts:312
          throw new TSError(formatDiagnostics(diagnosticList, cwd, ts, lineOffset))
                ^
TSError: ⨯ Unable to compile TypeScript
src/server/index.ts (1,23): Cannot find module 'child_process'. (2307)
src/server/index.ts (2,23): Cannot find module 'http'. (2307)
src/server/index.ts (3,21): Cannot find module 'fs'. (2307)
src/server/index.ts (5,26): Cannot find module 'express'. (2307)
src/server/index.ts (6,27): Cannot find module 'minimist'. (2307)
src/server/index.ts (8,20): Cannot find module '../assets/ts/utils/logger'. (2307)
src/server/index.ts (10,30): Cannot find module './socket_server'. (2307)
src/server/index.ts (11,42): Cannot find module './build_utils'. (2307)
src/server/index.ts (12,37): Cannot find module './webpack_configs'. (2307)
src/server/index.ts (16,5): Cannot find name 'process'. (2304)
src/server/index.ts (17,44): Cannot find name 'process'. (2304)
src/server/index.ts (38,7): Cannot find name 'process'. (2304)
src/server/index.ts (100,15): Cannot find name 'process'. (2304)
    at getOutput (/vimflowy/node_modules/ts-node/src/index.ts:312:17)
    at /vimflowy/node_modules/ts-node/src/index.ts:343:18
    at Object.compile (/vimflowy/node_modules/ts-node/src/index.ts:502:17)
    at Module.m._compile (/vimflowy/node_modules/ts-node/src/index.ts:406:44)
    at Module._extensions..js (module.js:579:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/vimflowy/node_modules/ts-node/src/index.ts:409:12)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Function.Module.runMain (module.js:604:10)
```

**Comment by mi-lee** [comment]
Never mind, the issue is fixed alongside v.3.1.0 in https://github.com/TypeStrong/ts-node/issues/220.
