### ISSUE TITLE
errors.assert gives worse test output.

### ISSUE THREAD

**Issue by za3k** [WuTheFWasThat/vimflowy#80]
Example output before adding an assert:

    174) zoom doesnt allow unindenting out:
     TypeError: Cannot read property 'id' of undefined
    at Data.getLine (assets/js/data.coffee:78:31)
    at Cursor._getPropertiesFromContext (assets/js/cursor.coffee:311:18)
    at new Cursor (assets/js/cursor.coffee:15:9)
    at new View (assets/js/view.coffee:214:21)
    at new TestCase (test/testcase.coffee:28:17)
    at Context.<anonymous> (test/tests/zoom.coffee:150:13)

After adding `errors.assert row?.id, "row is undefined"`:

    174) zoom doesnt allow unindenting out:
     Assertion error: row is undefined
    Expected undefined to be true
    Error
    at errorFactory (/home/zachary/vimflowy/assets/js/errors.coffee:8:23)
    at exports.undefined.window.errors (/home/zachary/vimflowy/assets/js/errors.coffee:24:20)
    at Object.<anonymous> (/home/zachary/vimflowy/assets/js/errors.coffee:4:1)
    at Object.<anonymous> (/home/zachary/vimflowy/assets/js/errors.coffee:1:1)
    at Module._compile (module.js:435:26)
    at Object.loadFile (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/zachary/vimflowy/assets/js/datastore.coffee:3:19)
    at Object.<anonymous> (/home/zachary/vimflowy/assets/js/datastore.coffee:1:1)
    at Module._compile (module.js:435:26)
    at Object.loadFile (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/zachary/vimflowy/test/testcase.coffee:6:13)
    at Object.<anonymous> (/home/zachary/vimflowy/test/testcase.coffee:1:1)
    at Module._compile (module.js:435:26)                                                                                                      [0/1920]
    at Object.loadFile (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/zachary/vimflowy/test/testcase.coffee:6:13)
    at Object.<anonymous> (/home/zachary/vimflowy/test/testcase.coffee:1:1)
    at Module._compile (module.js:435:26)
    at Object.loadFile (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/zachary/vimflowy/test/tests/backspace.coffee:1:12)
    at Object.<anonymous> (/home/zachary/vimflowy/test/tests/backspace.coffee:1:1)
    at Module._compile (module.js:435:26)
    at Object.loadFile (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:16:19)
    at Module.load (/home/zachary/vimflowy/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /home/zachary/vimflowy/node_modules/mocha/lib/mocha.js:216:27
    at Array.forEach (native)
    at Mocha.loadFiles (/home/zachary/vimflowy/node_modules/mocha/lib/mocha.js:213:14)
    at Mocha.run (/home/zachary/vimflowy/node_modules/mocha/lib/mocha.js:453:10)
    at Object.<anonymous> (/home/zachary/vimflowy/node_modules/mocha/bin/_mocha:393:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3

**Comment by WuTheFWasThat** [comment]
i don't understand why this happens :(
